### ISSUE TITLE
I found a bug

### ISSUE THREAD

**Issue by guanglinchen** [nathancheek/INA220#6] opened 2023-12-29 14:44 UTC
ina22o.h  
I think enum ina_Adc_Mode the value should not be hexadecimal
--------------------------------------------------
  {
    INA_ADC_MODE_9BIT   =  0x0,
    INA_ADC_MODE_10BIT  =  0x1,
    INA_ADC_MODE_11BIT  =  0x2,
    INA_ADC_MODE_12BIT  =  0x3,
    INA_ADC_MODE_2AVG   =  0x9,
    INA_ADC_MODE_4AVG   = 0x10,
    INA_ADC_MODE_8AVG   = 0x11,
    INA_ADC_MODE_16AVG  = 0x12,
    INA_ADC_MODE_32AVG  = 0x13,
    INA_ADC_MODE_64AVG  = 0x14,
    INA_ADC_MODE_128AVG = 0x15
  }; // of enumerated type

correct:
---------------------------------------------------
  {
    INA_ADC_MODE_9BIT   =  0,
    INA_ADC_MODE_10BIT  =  1,
    INA_ADC_MODE_11BIT  =  2,
    INA_ADC_MODE_12BIT  =  3,
    INA_ADC_MODE_2AVG   =  9,
    INA_ADC_MODE_4AVG   = 10,
    INA_ADC_MODE_8AVG   = 11,
    INA_ADC_MODE_16AVG  = 12,
    INA_ADC_MODE_32AVG  = 13,
    INA_ADC_MODE_64AVG  = 14,
    INA_ADC_MODE_128AVG = 15
  }; // of enumerated type

**Comment by Raurmar** [comment] 2023-12-30 15:57
I found the same issue yesterday. 

I correctet the shown DEC Values to the right HEX Values.

IS:
______________________________________________________________
{
INA_ADC_MODE_9BIT = 0x0,
INA_ADC_MODE_10BIT = 0x1,
INA_ADC_MODE_11BIT = 0x2,
INA_ADC_MODE_12BIT = 0x3,
INA_ADC_MODE_2AVG = 0x9,
INA_ADC_MODE_4AVG = 0x10,
INA_ADC_MODE_8AVG = 0x11,
INA_ADC_MODE_16AVG = 0x12,
INA_ADC_MODE_32AVG = 0x13,
INA_ADC_MODE_64AVG = 0x14,
INA_ADC_MODE_128AVG = 0x15
}; // of enumerated type

Should be:
==========================================
{
INA_ADC_MODE_9BIT = 0x0,
INA_ADC_MODE_10BIT = 0x1,
INA_ADC_MODE_11BIT = 0x2,
INA_ADC_MODE_12BIT = 0x3,
INA_ADC_MODE_2AVG = 0x9,
INA_ADC_MODE_4AVG = 0xA,
INA_ADC_MODE_8AVG = 0xB,
INA_ADC_MODE_16AVG = 0xC,
INA_ADC_MODE_32AVG = 0xD,
INA_ADC_MODE_64AVG = 0xE,
INA_ADC_MODE_128AVG = 0xF
}; // of enumerated type

Testet it today and now the Config Register of the INA220 is correct.

The lib works because in the INA::begin the config will be added to a 0xF.

this->configRegister |= (busAdcMode & 0xF)   << INA220_BADC_FIRST_BIT; // Mask off unused bits then shift in the bus ADC mode
  this->configRegister |= (shuntAdcMode & 0xF) << INA220_SADC_FIRST_BIT; // Mask off unused bits then shift in the shunt ADC mode
  
 So if you select ADC_Mode_32AVG the Outcome should be 0xFD.
 At the moment the Outcome ist 0xF3, which responds to the 12bit ADC mode. 
 
 Switched two INA's on my Board because I thougt they were defect... 
 
 Nevertheless now it works.
 Happy New Year. 
 And thanks for the Work on the Lib.

**Comment by nathancheek** [comment] 2023-12-31 05:15
Thank you both for reaching out with this bug report. I concur this was a mistake, and have pushed a fix.

I also made a couple other small code fixes which shouldn't affect functionality, such as making the `INA220_CONFIG_PG_MASK` match the same format as the other masks.

Please test it out and let me know if you have any additional issues.

**Comment by Raurmar** [comment] 2024-01-01 21:50
Hey there,

Tested it today and it now works as intended. 

I have not found any more issues this far.

**Closed** 2024-01-03 02:16 UTC
Labels: bug
